//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace navettes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonnement
    {
        public int id { get; set; }
        public Nullable<System.DateTime> dateDebut { get; set; }
        public Nullable<System.DateTime> dateFin { get; set; }
        public Nullable<int> idoffre { get; set; }
        public Nullable<int> idusr { get; set; }
    
        public virtual Offre Offre { get; set; }
        public virtual Voyageur Voyageur { get; set; }
    }
}
