//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace navettes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demande
    {
        public int id { get; set; }
        public string fromCity { get; set; }
        public string toCity { get; set; }
        public Nullable<System.TimeSpan> timeGo { get; set; }
        public Nullable<System.TimeSpan> timeWent { get; set; }
        public Nullable<int> idusr { get; set; }
    
        public virtual Voyageur Voyageur { get; set; }
    }
}
