//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace navettes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Offre()
        {
            this.Abonnement = new HashSet<Abonnement>();
        }
    
        public int id { get; set; }
        public Nullable<int> NmbAbone { get; set; }
        public Nullable<bool> Stiuation { get; set; }
        public Nullable<double> prix { get; set; }
        public Nullable<int> idnvt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abonnement> Abonnement { get; set; }
        public virtual Navette Navette { get; set; }
    }
}
