//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace navettes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voyageur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voyageur()
        {
            this.Abonnement = new HashSet<Abonnement>();
            this.Demande = new HashSet<Demande>();
        }
    
        public int id { get; set; }
        public string CIN { get; set; }
        public string FirstName { get; set; }
        public string lastName { get; set; }
        public string EmailUSR { get; set; }
        public string mdpUSR { get; set; }
        public string tel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abonnement> Abonnement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Demande> Demande { get; set; }
    }
}
